config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'
  
  resources :movies, only: [:show, :index]
  
  

  resources :orders

  get '/who_bought', to: 'orders#who_bought'
   

  resource :cart, only: [:show] do
    put 'add/:movie_id', to: 'carts#add', as: :add_to
    put 'remove/:movie_id', to: 'carts#remove', as: :remove_from
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
    
  
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :relationships, foreign_key: "movie_id"
  has_many :orders, through: :relationships 
  
  def poster
    "http://www.kinopoisk.ru/images/film_big/#{poster_url}"
  end
 
  def imdb
    "http://www.kinopoisk.ru/film/#{imdb_id}/votes/"
  end

  def cart_action(current_user_id)
    if $redis.sismember "cart#{current_user_id}", id
      "Remove from"
    else
      "Add to"
    end
  end

  
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :relationships, foreign_key: "order_id", dependent: :destroy
	has_many :myorders, through: :relationships, source: :movie 
	validates :name,  presence: true, length:    { maximum: 50 }
	validates :address,:pay_type, :user_id,  presence: true
	default_scope -> { order('created_at DESC') }
	PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
	validates :pay_type, inclusion: PAYMENT_TYPES
	attr_accessible :name, :address, :email, :pay_type
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
	validates :email, presence: true, format: { with: email_regex }
	
	def addrelation(movie)

		self.relationships.create!(movie_id: movie) 
		
	end

	

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :order
  belongs_to :movie
  attr_accessible :order_id, :movie_id
  validates :movie_id, :order_id,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :order, dependent: :destroy

  def show_carts
  	cart_ids = $redis.smembers "cart#{id}"
    @cart_movies = User.find(cart_ids)
  end 

  def ordercount
    user=User.find(id)
    @orderscount=user.order.count
  end

  def cart_count
    $redis.scard "cart#{id}"
  end

  def moviesid
    $redis.smembers "cart#{id}"
  end

  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  include CurrentCart
  before_action :current_user_cart
  
  respond_to :html, :js

  def show
    if current_user.cart_count<=0 
      redirect_to root_url, notice: "Ваша корзина пустая!"
      return
    end
    cart_movies
  end
 
  def add
    $redis.sadd current_user_cart, params[:movie_id]
    render json: current_user.cart_count, status: 200
  end
 
  def remove
    clearcart(params[:movie_id])
    render json: current_user.cart_count, status: 200
  end
 
end

app/controllers/concerns/current_cart.rb
module CurrentCart
   extend ActiveSupport::Concern
  
  private
   
   

   def correct_user
      @user = User.find(current_user.id)
      rendirect_to(cart_url) unless current_user?(@user)
   end

   def current_user?(user)
    user == current_user
   end

   def current_user_cart
    "cart#{current_user.id}"
   end

   def cart_movies
	   @cart_ids =  current_user.moviesid 
     @cart_movies = Movie.find(@cart_ids)	
   end

   def order_movies(movieid)
   	 @order_movie = Movie.find(movieid)
   end

   def clearcart(movieid)
   	 $redis.srem current_user_cart, movieid   	
   end

 end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movies = Movie.all
  end

  
  def show
   @movie = Movie.find(params[:id])
   @cart_action = @movie.cart_action current_user.try :id 
  end

  
 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 
 include CurrentCart
 before_action :authenticate_user! 
 before_action :current_user_cart, only: [:show, :new, :create]
 before_action :set_order, only: [:show, :destroy]
 before_action :order_movie, only: [:show]
 before_action :morder, only: [:show]
 before_action :correct_user, only: [:index, :show]
 
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where("user_id = ?", current_user.id)
    
  end

  # GET /orders/1
  # GET /orders/1.json

  def show
    @myorder=@order.myorders
  end

  # GET /orders/new
  def new

    if current_user.cart_count<=0 
      redirect_to root_url, notice: "Ваша корзина пустая!"
      return
    end
    
    cart_movies
    @cartsid= current_user_cart
    @order = Order.new
    @count=@order.relationships.count

    
  end


  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create

    cart_movies
    @order = current_user.order.build(order_params)
    
    respond_to do |format|
      if @order.save
        @cart_ids.each do |movie| 
          @order.addrelation(movie)
          clearcart(movie)
        end        
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def who_bought

    @orders = Order.all  
    @latest_order = @orders.order(:updated_at).first
    if stale?(@latest_order)
     respond_to do |format|
       format.atom
     end
    end
  end

  private

    def morder
      redirect_to root_url unless @order.user_id==current_user.id
    end

    def order_movie
      @movie = @order.relationships
      redirect_to root_url if @movie.nil? 
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
      rescue
        redirect_to root_url 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	include CurrentCart

	def hidden_div_if(condition, attributes = {}, &block)

		if condition
			attributes["style"] = "display: none"
		end
		content_tag("li", attributes, &block)
	end

    def total
    	cart_movies
    	return @cart_movies.to_a.sum { |movie| movie.price }
    end

    def total_order
    	movie = @order.myorders
    	return movie.to_a.sum { |movie| movie.price }
    end

    def total_orders(order)
    	movie=order.myorders 
    	return movie.to_a.sum { |movie| movie.price }
    end

end

app/helpers/carts_helper.rb
module CartsHelper

	

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

	
   		

end

app/views/carts/_showcart.html.erb
 
  <% @cart_movies.each do |movie|%>

  <div data-equalizer class="cart-movie large-12 column mb1">
    <div class="column large-2 text-center p0" data-equalizer-watch>
      <%=link_to movie do%>
        <%=image_tag movie.poster, class: "radius-l1"%>
      <%end%>
    </div>
    <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
        <p class="scale ptm"> <%= movie.title %> </p>
    </div>
    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
      <%=link_to "" , data: {targetUrl: remove_from_cart_path(movie)}, remote: true do%>
        <i class="fi-x right"></i>
      <%end%>
      <h4 class="scale"> <%= number_to_currency(movie.price) %></h4>
    </div>
  </div>
  <%end%>
  <div class="row">
    <div class="large-3 mr1 right  small-3  columns primary-bg  radius-box" >
        <h7 id="total" class="scale"  > <%=  "Total price: " + number_to_currency(total) %> </h7>
    </div>
  </div>

app/views/carts/show.html.erb
 <div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>My Cart</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> movies!</p>
  </div>
  
  <%=  render "carts/showcart" %>

  <%= hidden_div_if(current_user.cart_count<=0, id: 'current_item') do %>
    
  	<div class="order large-3 right small-2  columns">
    	<%=link_to 'checkout', new_order_path , method: :get, class: " radius tiny button "%>
  	</div>
  
  <%end%>
   
    
</div>

app/views/carts/show.js.erb
$("#total").html('<%= "Total price: " + number_to_currency(total) %>')  

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_header.html.erb
<div class="row">
  <nav class="top-bar column" data-topbar>

    <ul class="title-area">
      <li class="name">
        <h1>
          <a href="/">
            <i class="fi-play-video"></i> MovieStore
          </a>
        </h1>
      </li>
      <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">

    <!-- Left Nav Section -->
    <ul class="left">
      <li class="has-form">
       <div class="row collapse">
        <div class="large-8 small-9 columns">
          <input type="text" class="radius expand" placeholder="Find Movie">
        </div>
        <div class="large-4 small-3 columns ">
         <a href="#" class="nice  radius small button columns">Search</a>
        </div>
       </div>
      </li>
    </ul>

      <!-- Right Nav Section -->
    <ul class="right">
     <%if signed_in?%>
       <%= hidden_div_if(current_user.cart_count<=0, id: 'current_item') do %>
         <%= link_to cart_path do%>
             <i class="fi-shopping-cart "></i> My Cart (<span class="cart-count"><%=current_user.cart_count%></span>)
          <%end%>
       <%end%>
       <%= hidden_div_if(current_user.ordercount<=0, id: 'current_order') do %>
        <%=link_to "My orders: #{current_user.ordercount}", orders_path%> 
       <%end%>
       <li><%=link_to current_user.email, edit_user_registration_path%></li>
       <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
     <%else%>
       <li><%=link_to "Register", new_user_registration_path%></li>
       <li><%=link_to "Login", new_user_session_path%></li>
     <%end%>
    </ul>

   

    </section>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "movie" %></title>
    <link rel="shortcut icon" href="<%=asset_path("logo.png")%>" >

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>
    <%= render "layouts/alerts" %>
   
    <div id="main-content" class="row full-min-height">
       <%= yield %>
    </div>

    <footer class="row">
     <div class="large-12 columns">
       <hr> <p>© MovieStore 2015</p> 
     </div>
    </footer> 
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/movies/index.html.erb
<h4 class="column">Featured Movies</h4>
<div class="column">
  <ul class="movies-grid no-bullet row">
    <% @movies.each do |movie| %>
      <li class="large-4 medium-4 small-12 column">
        <div class="movie-card padly">
          <%= link_to movie, class: "poster" do %>
            <%= image_tag movie.poster %>
          <% end %>
          <div class="movie-info ell glassy-bg padmy padlx">
            <div class="title"  >
              <h6 ><%= movie.title %> <span>(<%= movie.release_year %>)</span></h6>
            </div>
            <p class="left price label movie-label radius"><%= number_to_currency(movie.price) %></p>
            <%= link_to movie.imdb, class: "right" do %>
              <%= image_tag asset_path("imdb_logo.png") %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/movies/show.html.erb
<div class="large-3 small-12 column">
  <%=image_tag @movie.poster%>
</div>
<div class="large-9 small-12 column">
  <h3>
    <%= @movie.title %>
    (<%= @movie.release_year %>)
    <%=link_to @movie.imdb do%>
      <%=image_tag asset_path("imdb_logo.png")%>
    <%end%>
  </h3>
  <p class="label movie-label radius mb1"> <%= number_to_currency(@movie.price) %></p>

  <p><%= @movie.description %></p>

  <%if signed_in?%>
    <%=link_to "", class: "button", data: {target: @cart_action, addUrl: add_to_cart_path(@movie), removeUrl: remove_from_cart_path(@movie)} do%>
      <i class="fi-shopping-cart"></i>
      <span><%=@cart_action%></span> Cart
    <%end%>
  <%end%>
</div>

app/views/orders/_allorder.html.erb
 <%@orders.each do |order|%>
   <div data-equalizer class="cart-movie large-12 column mb1">
    <div class="column large-2 primary-bg text-center radius-l1 " data-equalizer-watch>
      <%=link_to  order do%>
       <h6 class="cale fi-shopping-cart"> <%= "Номер заказа: #{order.id}" %> </h6>
      <%end%>
    </div>
    <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
        <p class=" ptm"> <%="Сформирован на имя #{order.name}, придет по адрессу #{order.address}. Дата создания заказа #{order.created_at}"%> </p>
    </div>
    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
      <%=link_to ""  do%>
        <i class=" right"></i>
      <%end%>
      <h6 class="scale ca">  <%=  "Total price: " + number_to_currency(total_orders(order)) %></h6>
    </div>
   </div>
  
  <%end%>

app/views/orders/_form.html.erb
  <fieldset>
   <legend>Enter the details for ordering</legend>
   <%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
       <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
       </ul>
     </div>
    <% end %>

   <div class="field">
      <%= f.label :name %><br>&nbsp
      <%= f.text_field :name, size: 40  %>
    </div>
    <div class="field">
      <%= f.label :address %><br>&nbsp
      <%= f.text_area :address, rows:3, cols:40  %>
    </div>
    <div class="field">
      <%= f.label :email %><br>&nbsp
      <%= f.text_field :email, size: 40 %>
    </div>
    <div class="field button-group">
      <%= f.label :pay_type %><br>&nbsp
      <%= f.select :pay_type, Order::PAYMENT_TYPES, prompt: 'Select a payment method' %>
    </div>
    <div class="row"> 
      <div class="large-6 large-offset-4 small-2 columns", type="submit">
        <%= f.submit 'Place Order', class: "sub radius small button"  %>
      </div>
    </div>
   <% end %>
  </fieldset>   

app/views/orders/_showorder.html.erb
 
 <%@myorder.each do |movie|%>
   <div data-equalizer class="cart-movie large-12 column mb1">
    <div class="column large-2 text-center p0" data-equalizer-watch>
      <%=link_to  movie do%>
        <%=image_tag  movie.poster, class: "radius-l1"%>
      <%end%>
    </div>
    <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
        <p class="scale ptm"> <%=  movie.title %> </p>
    </div>
    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
      <%=link_to ""  do%>
        <i class=" right"></i>
      <%end%>
      <h4 class="scale"> <%= number_to_currency(movie.price) %></h4>
    </div>
  </div>
 <%end%>
  
  <div class="row">
    <div class="large-3 mr15   right  small-3  columns primary-bg  radius-box mrm" >
        <h7 id="total" class="scale "  > <%=  "Total price: " + number_to_currency(total_order) %> </h7>
    </div>
  </div>
  
  

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4><%="My Orders" %></h4>
  </div>
  
  <%=  render "orders/allorder" %>

 

</div>

app/views/orders/new.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>to buy movies</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> movies!</p>
  </div>

  <%=  render "carts/showcart" %>
  <div class="depot_form">

        <%= render 'form' %>

  </div>
  <div class="row">
      <div class="large-5 columns"></div>
      <div class="large-3   small-3  columns">
        <%=link_to 'back', cart_path, method: :get, class: "radius tiny button "%>
      </div>
    </div>
</div>

app/views/orders/new.js.erb
$("#total").html('<%= "Total price: " + number_to_currency(total) %>')  

app/views/orders/show.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">

  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4><%="Order: N-#{@order.id}. Сформирован на имя #{@order.name}, придет по адрессу #{@order.address}. Дата создания заказа #{@order.created_at}"%></h4>
    
  </div>
  
  <%=  render "orders/showorder" %>

  <div class="row">
  	<div class="order large-4 left small-2  columns mlm" >
       	<h7 class="scale"  > <%=  link_to "DELETE Order: N-#{@order.id}", @order, method: :delete, data: { confirm: "You sure?" }, title: "Order: N-#{@order.id}", class: " radius tiny button mlm "  %> </h7>
    </div>
   	<div class="order large-4  small-2  columns mrm"> 
    	<%=link_to 'PAY for your order', '#' , method: :get, class: "radius  button mrm "%>
  	</div>
    
  </div>
	
</div>